constants:
  jwt:
    issuer: otd@otd.com
    schema: Bearer

    claim-key: signedUser

    header-key: Authorization
    secret-key: DaeguGreenArtAcademyClass502RoomForProjectOneTwoDayFighting

    access-token-cookie-name: access-token


#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8081/eureka
#
#  #   status 이름 변경 부분
#  instance:
#    prefer-ip-address: true
#    ip-address: ${server.address}
#    instance-id: ${server.address}:${server.port}


#
#spring:
#  cloud:
#    kubernetes:
#      discovery:
#        enabled: true
#      reload:
#        enabled: true
#        strategy: refresh
#    gateway:
#      server:
#        webflux:
#          discovery:
#            locator:
#              enabled: true
#              lower-case-service-id: true
#          routes:
#            - id: otd-life
#              uri: lb://otd-life
#              predicates:
#                - Path=/api/OTD/life/**
#
#            - id: otd-user
#              uri: lb://otd-user
#              predicates:
#                - Path=/api/user/**, /pic/profile/**, /oauth2/authorization/**, /api/otd/**
#


server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: OTD-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: otd-life
#              uri: lb://OTD-LIFE
              uri : http://localhost:8083
              predicates:
                - Path=/api/OTD/life/**,/api/OTD/meal/**,/api/OTD/exercise_record/**,/api/OTD/community/**,/api/OTD/exercise/**,/api/OTD/body_composition/**,/api/OTD/waterIntake/**,/api/OTD/admin2/**,/api/OTD/notifications/**,/static/community/**

            - id: otd-user
#              uri: lb://OTD-USER
              uri : http://localhost:8082
              predicates:
                - Path=/api/OTD/user/**,/api/OTD/user/reissue/**,/api/OTD/profile/**,/oauth2/authorization/**,/api/OTD/email/**,/api/OTD/challenge/**,/home/green/download/challenge/**,/files/**,/profile/**,/api/OTD/admin/**,/api/OTD/pointshop/**


  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure=INFO: