eureka:
  client:
    enabled: false

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: otd-life
              uri: lb://otd-life
              predicates:
                - Path=/api/OTD/life/**

            - id: otd-user
              uri: lb://otd-user
              predicates:
                - Path=/api/OTD/user/**, /pic/profile/**, /oauth2/authorization/**
constants:
  jwt:
    issuer: otd@otd.com #토큰 발행자
    bearer-format: JWT

    claim-key: signedUser
    header-key: Authorization
    secret-key: DaeguGreenArtAcademyClass502RoomForProjectOneTwoDayFighting

    domain: greenart.n-e.kr

    access-token-cookie-name: access-token
