constants:
  jwt:
    issuer: otd@otd.com
    schema: Bearer

    claim-key: signedUser

    header-key: Authorization
    secret-key: DaeguGreenArtAcademyClass502RoomForProjectOneTwoDayFighting

    access-token-cookie-name: access-token


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka

  #   status 이름 변경 부분
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}

server:
  port: 8080
  address: localhost
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: OTD-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://OTD-USER
              predicates:
                - Path=/api/OTD/user/**, /pic/profile/**, /oauth2/authorization/**
            - id: life
              uri: lb://OTD-life
              predicates:
                - Path=/api/OTD/life/**



  jackson:
    default-property-inclusion: non_null

