management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: otd-life
              uri: lb://otd-life
              predicates:
                - Path=/api/OTD/life/**,/api/OTD/meal/**,/api/OTD/exercise_record/**,/api/OTD/community/**,/api/OTD/exercise/**,/api/OTD/body_composition/**,/api/OTD/waterIntake/**,/api/OTD/admin2/**,/api/OTD/notifications/**,/static/community/**

            - id: otd-user
              uri: lb://otd-user
              predicates:
                - Path=/api/OTD/user/**,/api/OTD/user/reissue/**,/api/OTD/profile/**,/oauth2/authorization/**,/api/OTD/email/**,/api/OTD/challenge/**,/home/green/download/challenge/**,/files/**,/profile/**,/api/OTD/admin/**,/api/OTD/pointshop/**

